config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  resources :directories do
    collection do
      post 'scan'
    end
  end

end

app/models/directory.rb
class Directory < ActiveRecord::Base
  validates_uniqueness_of :path

  class << self
    def scan
      Directory.scan_directory('/Users/Larry/Movies')
    end

    def get_film_files(path)
      files = []

      Dir.foreach(path) do |item|
        next if item == '.' or item == '..'

        item_path = "#{path}/#{item}"

        unless File.directory? item_path
          if File.extname(item_path).downcase =~ /rmvb|avi|mp4|mkv/
            files << item
          end
        end
      end

      files
    end

    def scan_directory(path)
      Dir.foreach(path) do |item|
        next if item == '.' or item == '..'

        item_path = "#{path}/#{item}"

        if File.directory? item_path
          Directory.scan_directory(item_path)
        else
          if File.extname(item_path).downcase =~ /rmvb|avi|mp4|mkv/
            logger.info "creating #{path}"
            Directory.create(:path => path)
          end
        end
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/directories_controller.rb
class DirectoriesController < ApplicationController
  def index
    @directories = Directory.all
  end

  def show
    @directory = Directory.find(params[:id])
    @film_files = Directory.get_film_files(@directory.path)
  end

  def scan
    Directory.scan
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/directories_helper.rb
module DirectoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/directories/index.html.erb
<ul>
<% @directories.each do |dir| %>
  <li><%= link_to dir.path, directory_path(dir) %></li>
<% end %>
</ul>

app/views/directories/scan.js.erb
$('#scan-button').replaceWith($('<span>Scan completed</span>'));

app/views/directories/show.html.erb
<h2>In <%= @directory.path %> found <%= @film_files.count %> films.

<ul>
<% @film_files.each do |file| %>
  <li><%= file %></li>
<% end %>
</ul>

app/views/home/index.html.erb
<h1>Homepage</h1>

<div>
<%= link_to 'Start Scan', scan_directories_path, :id => 'scan-button', :method => :post, :remote => true %>
</div>

<br>
<br>

<div>
  Now we have <%= Directory.count %> directories that contains movies.  <%= link_to 'Go to see more >>', directories_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Films</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>